version: "3"
services:
  frontend:
    image: epauldike/birfe:1
    restart: always
    depends_on:
      - backend
    ports:
      - 56:3000

  backend:
    image: epauldike/bibe:1
    restart: always
    depends_on:
      - mongodb
    ports:
      - 20:4343

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books_i_read
